# Generated by Django 3.2.15 on 2022-12-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvesting', '0049_alter_harvester_harvester_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestableTimeResource',
            fields=[
                ('harvestableresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='harvesting.harvestableresource')),
                ('has_time', models.BooleanField(default=False)),
            ],
            bases=('harvesting.harvestableresource',),
        ),
    ]
